# Site settings
title:          KumiPensa
description:    "Knowlodge is a search for the true"
image: https://marovski.github.io/css/img/portraitMarovski.png
url: https://marovski.github.io/KumiPensaBlog/




# Author
author:
  name:         Mário Cardoso
  url:          https://marovski.github.io
  

# Build settings
markdown:       kramdown


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
