# Site settings
title:          Marovski
description:    "Minimal Jekyll theme for storytellers"

url:            "https://chesterhow.github.io"

# Author
author:
  name:         Mario Cardozo
  url:          https://marovski.github.io
  email:        cardozo27cv@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins_dir:
  - jekyll-feed
  - jekyll-paginate
  - jemoji 
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
