# Site settings
title:          KumiPensa
description:    "Knowlodge is a search for the true"



# Author
author:
  name:         Mario Cardozo
  url:          https://marovski.github.io
  email:        cardozo27cv@gmail.com

# Build settings
markdown:       kramdown


# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems

plugins:
  - jekyll-feed
  - jekyll-paginate
  
# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
